# Generated by Django 4.0.4 on 2022-04-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20220412_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredienthistory',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ingredientstock',
            name='date_purchased',
            field=models.DateTimeField(),
        ),
    ]
