# Generated by Django 3.2.5 on 2022-04-11 19:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PURCHASE', 'purchase'), ('CONSUME', 'consume')], default='purchase', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('ingredient_id', models.PositiveIntegerField()),
                ('amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('unit', models.CharField(max_length=50)),
                ('calories', models.IntegerField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('carbs', models.IntegerField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('fat', models.IntegerField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('protein', models.IntegerField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('sodium', models.IntegerField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('sugar', models.IntegerField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('date_purchased', models.DateTimeField(auto_now_add=True)),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.ingredientstock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='IngredientPurchased',
        ),
    ]
