# Generated by Django 3.2.5 on 2022-04-11 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20220412_0307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredienthistory',
            options={'ordering': ['created']},
        ),
        migrations.RenameField(
            model_name='ingredienthistory',
            old_name='date_purchased',
            new_name='created',
        ),
    ]
