# Generated by Django 3.2.5 on 2022-04-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20220412_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredienthistory',
            name='type',
            field=models.CharField(choices=[('PURCHASE', 'purchase'), ('CONSUME', 'consume')], default='purchase', max_length=20),
        ),
    ]
