# Generated by Django 3.2.5 on 2022-04-11 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_ingredienthistory_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredienthistory',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='ingredienthistory',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.ingredientstock'),
        ),
        migrations.AlterField(
            model_name='ingredienthistory',
            name='type',
            field=models.CharField(max_length=20),
        ),
    ]
